# Generated by Django 5.2 on 2025-05-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر')),
                ('category', models.CharField(choices=[('humic', 'کود هیومیک اسید'), ('apartment', 'گیاهان آپارتمانی')], max_length=20, verbose_name='دسته\u200cبندی')),
            ],
        ),
    ]
